---
- name: Copy Api Files
  shell: mkdir -p /opt/jentcrypto/wwwroot

- name: Copy config to jetcrypto
  template:
    src: appsettings.json
    dest: /opt/jetcrypto/appsettings.json

- name: Copy config to jetcrypto appsettings.Development.json
  template:
    src: appsettings.Development.json
    dest: /opt/jetcrypto/appsettings.Development.json

- name: Register Microsoft key and feed
  apt:
    deb: wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb


- name: Install https Repository Access
  apt:
    name: apt-transport-https
    state: latest
    update_cache: yes

- name: Install .NET SDK
  apt:
    name: dotnet-sdk-2.1
    state: latest
    update_cache: yes

- name: Install Redis
  apt:
    name: redis-server
    state: latest
    update_cache: yes
        
- name: Set addres Redis-server to Localhost
  shell: echo "127.0.0.1 redis01.Bytewerk.local" >> /etc/hosts
  notify: restart jetcrypto service
