---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  tags: nginx

- name: Configure nginx Jetcripto Host
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: jetcrypto.conf, dest: /etc/nginx/sites-enabled/jetcrypto.conf }
    - { src: nginx.conf, dest: /etc/nginx/nginx.conf }
    - { src: gzip.conf, dest: /etc/nginx/conf.d/gzip.conf }
  tags: nginx
  notify: restart nginx service
